name: Visual regression PR gate

on:
  pull_request:
    branches:
      - master

jobs:
  vr-gate:
    uses: ./.github/workflows/vr-gate.yml
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
